### ISSUE TITLE
Dropping data_status from entire database

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#51]
Column names 'data_status' is present in 44 tables. Yet, it always has either of those five values:
 - "published"
 - "public"
 - ""
 - "public_default"
 - "public available under MTA"

Can we assume all that means "public" and remove that column from the DB entirely?

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, do we have your "go ahead" about that?

**Comment by wjurkowski** [comment]
Yes, we assume all data is public. But if its published that's another
matter. Do we have a field somewhere that could store the Pubmed ID of the
paper (if any)?

2015-03-27 10:42 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
About pubmed id i don't know. There was a dedicated cs_publications table in the CS schema, but it was empty. We may, however, introduce a pubmedid field where you find it useful - and the users may supply that value when submitting data. Out of your proposed submissions (populations, traits, qtl, linkage_map) which one could be accompanied by a pubmedid?

**Comment by Nuanda** [comment]
@nowakowski Piotr, please drop data_status field from all the tables it is present in. That means - "a tremendous amount" of tables :).

**Comment by wjurkowski** [comment]
Lets leave it for discussion...

2015-03-27 12:17 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Sure we can leave the pubmedid discussion open. I asked Piotr to drop the useless (and very frequent!) data_status table.

**Comment by nowakowski** [comment]
Addressed in PR #80.

**Comment by sarahcayling** [comment]
We discussed the pubmed id issue, and there could be pubmed ids on plant trials (related to traits), QTL or on linkage maps. Probably not a population alone without these other things.

**Comment by Nuanda** [comment]
Thanks - I made a note about that in #77

**Comment by Nuanda** [comment]
@nowakowski I still see `data_status` fields in `occasions` and `linkage_groups` tables. Please remove them as well (no useful data inside).

**Comment by Nuanda** [comment]
Related #132
